import unittest
import logging
from rt_with_exceptions import Runner


logging.basicConfig(
    level=logging.INFO,
    filename='runner_tests.log',
    filemode='w',
    encoding='UTF-8',
    format='%(asctime)s | %(levelname)s | %(message)s',
)

class RunnerTest(unittest.TestCase):
    def test_walk(self):
        try:
            runner = Runner(name="Test Runner", speed=-5)
            self.assertTrue(runner.is_walking())
            logging.info('"test_walk" выполнен успешно')
        except ValueError as e:
            logging.warning(f"Неверная скорость для Runner: {e}", exc_info=True)

    def test_run(self):
        try:
            runner = Runner(name=12345, speed=10)
            self.assertTrue(runner.is_running())
            logging.info('"test_run" выполнен успешно')
        except TypeError as e:
            logging.warning(f"Неверный тип данных для объекта Runner: {e}", exc_info=True)

if __name__ == '__main__':
    unittest.main()
